spring.application.name=eqrid_website
server.port=8080

# JSP view resolver
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/eqrid_db
spring.datasource.username=root
spring.datasource.password=Ravi@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

